package me.saharnooby.lib.query.query.api;

import lombok.NonNull;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

/**
 * Базовый контракт для любого SQL-запроса.
 */
public interface SqlQuery {

    /**
     * Возвращает SQL-строку с плейсхолдерами (?).
     */
    String getSql();

    /**
     * Возвращает список параметров для плейсхолдеров в порядке следования.
     */
    List<Object> getParams();

    /**
     * Подготавливает PreparedStatement и устанавливает параметры.
     * Этот метод реализован по умолчанию и подходит для всех запросов.
     */
    default PreparedStatement prepare(@NonNull Connection conn)
            throws SQLException {
        return prepare(conn, Statement.NO_GENERATED_KEYS);
    }

    /**
     * Подготавливает PreparedStatement с возможностью возврата ключей.
     */
    default PreparedStatement prepare(@NonNull Connection conn,
                                      int autoGeneratedKeys) throws SQLException {

        PreparedStatement ps = conn.prepareStatement(getSql(), autoGeneratedKeys);
        List<Object> params = getParams();

        for (int i = 0; i < params.size(); i++) {
            ps.setObject(i + 1, params.get(i));
        }

        return ps;

    }
}
